export const SAVE_CUSTOMER = "SAVED_CUSTOMER";
export const DEPOSIT_INFO = "DEPOSIT_INFO";
export const WITHDRAW_INFO = "WITHDRAW_INFO";
export const TRANSFER_INFO = "TRANSFER_INFO";
export const FETCH_ALL_DATA = "FETCH_ALL_DATA";
export const SINGLE_ACCOUNT = "SINGLE_ACCOUNT";
